name: Install Packages and Run Script on Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_and_execute:
    runs-on: ubuntu-20.04  # Specifies that the job should run on Ubuntu 20.04.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
        chmod 644 ~/.ssh/id_ed25519.pub
        ssh-keyscan github.com >> ~/.ssh/known_hosts  # This step ensures GitHub's host is known

    - name: Run Tesla Installation Script
      run: |
        chmod +x ./install.sh
        ./install.sh

